# config/default.yaml
sim:
  dt_s: 1.0
  speed: 1.0
  seed: 123

stations:
  P1:
    wet_well:
      area_m2: 6.0
      level_min_m: 0.6
      level_start_m: 1.2
      level_max_m: 1.8
      initial_level_m: 1.3
    pumps:
      - name: P1_A
        q_nom_m3s: 0.015
        efficiency: 0.65
      - name: P1_B
        q_nom_m3s: 0.015
        efficiency: 0.65
    flowmeter:
      tolerance_rel: 0.25
      fail_delay_s: 10.0

  P2:
    wet_well:
      area_m2: 8.0
      level_min_m: 0.7
      level_start_m: 1.4
      level_max_m: 2.1
      initial_level_m: 1.2
    pumps:
      - name: P2_A
        q_nom_m3s: 0.020
        efficiency: 0.62
      - name: P2_B
        q_nom_m3s: 0.020
        efficiency: 0.62
    flowmeter:
      tolerance_rel: 0.25
      fail_delay_s: 10.0

inflows:
  O1:
    base_m3s: 0.001
    peak_m3s: 0.001
    peak_hours: [7, 8, 19, 20, 21]
    noise_sigma: 0.30

  O2_alongline:
    base_m3s: 0.003
    peak_m3s: 0.012
    peak_hours: [6, 7, 18, 19, 20]
    noise_sigma: 0.35

  O2_extra:
    constant_m3s: 0.002
